######################################################################
# Automatically generated by qmake (3.0) ?? 2? 25 22:45:34 2014
######################################################################

TEMPLATE = app
TARGET = test_qt
INCLUDEPATH += .

# Input
HEADERS += test_qt_exp.h
SOURCES += test_qt_main.cpp test_qt_exp.cpp

